Création de noeuds fetchers pour paralléliser le traitement de lecture des différentes sources de flux (#19)
* init signatures fonctions fetchers
clean code mort main_agent.py

* mise à jour du graph LangGraph : dispatch_node, fetch_rss_node et merge_articles ainsi que les transitions

* refacto pour 1 noeud par sources pour fetch en // et merge à la fin
main_agent.py clean code

* ajout fetcher bluesky node
le graphe devient

                            +-----------+
                            | __start__ |
                            +-----------+
                                  *
                                  *
                                  *
                            +----------+
                            | dispatch |*
                        ****+----------+ ****
                    ****          *          ****
                ****               *             ****
             ***                   *                 ***
+---------------+          +--------------+          +-----------+
| fetch_bluesky |          | fetch_reddit |          | fetch_rss |
+---------------+***       +--------------+      ****+-----------+
                    ****           *         ****
                        ****      *      ****
                            ***   *   ***
                         +----------------+
                         | merge_articles |
                         +----------------+
                                  *
                                  *
                                  *
                             +--------+
                             | filter |
                             +--------+
                                  *
                                  *
                                  *
                            +-----------+
                            | summarize |
                            +-----------+
                                  *
                                  *
                                  *
                          +---------------+
                          | displayoutput |
                          +---------------+
                                  *
                                  *
                                  *
                        +-----------------+
                        | savedbsummaries |
                        +-----------------+
                                  *
                                  *
                                  *
                          +---------------+
                          | sendsummaries |
                          +---------------+
                                  *
                                  *
                                  *
                            +---------+
                            | __end__ |
                            +---------+

* cache fichier json

* fix lecture reddit / bluesky
.env : +BLUESKY_FILE

* refacto : allégement fetch_nodes.py -> utils_fetch_nodes.py

* ajout activation / désactivation des fetchers
fix affiche du nombre d'articles à résumer
_fill_flexible_slots dans select_articles_for_summary commenté pour l'instant, à reprendre + fix MAX_DAYS non utilisé
clean code

* fix _fill_flexible_slots

* docs docker
comments .env.example

* init refacto main_agent fetchers / noeuds + clean code

* init refacto fetchers création

* erreur circulaire d'import

$ python main_agent.py
Traceback (most recent call last):
  File "D:\wutemp\p8\workspace\techno_watch_ia\main_agent.py", line 49, in <module>
    from services.utils_fetchers import register_fetchers_auto
  File "D:\wutemp\p8\workspace\techno_watch_ia\services\utils_fetchers.py", line 11, in <module>
    from services.fetchers.rss_fetcher import RSSFetcher
  File "D:\wutemp\p8\workspace\techno_watch_ia\services\fetchers\rss_fetcher.py", line 12, in <module>
    from services.utils_fetchers import fetcher_class
ImportError: cannot import name 'fetcher_class' from partially initialized module 'services.utils_fetchers' (most likely due to a circular import) (D:\wutemp\p8\workspace\techno_watch_ia\ser
vices\utils_fetchers.py)

* utilisation de l'auto registry des fetchers par annotations et fix imports

* activation @fetcher_class pour RedditFetcher et BlueskyFetcher

* clean code

* logger : +print_color

* renommage annotations en decorator

---------

Co-authored-by: Olivier Duval <olivier.duval@univ-paris8.fr>