erreur circulaire d'import
$ python main_agent.py
Traceback (most recent call last):
  File "D:\wutemp\p8\workspace\techno_watch_ia\main_agent.py", line 49, in <module>
    from services.utils_fetchers import register_fetchers_auto
  File "D:\wutemp\p8\workspace\techno_watch_ia\services\utils_fetchers.py", line 11, in <module>
    from services.fetchers.rss_fetcher import RSSFetcher
  File "D:\wutemp\p8\workspace\techno_watch_ia\services\fetchers\rss_fetcher.py", line 12, in <module>
    from services.utils_fetchers import fetcher_class
ImportError: cannot import name 'fetcher_class' from partially initialized module 'services.utils_fetchers' (most likely due to a circular import) (D:\wutemp\p8\workspace\techno_watch_ia\ser
vices\utils_fetchers.py)